# Generated by Django 5.0.2 on 2024-03-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_rename_ventas_venta_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['nombreVendedor', 'nombreComprador']},
        ),
        migrations.RemoveField(
            model_name='venta',
            name='fechaDeCompra',
        ),
        migrations.AddField(
            model_name='venta',
            name='nombreProducto',
            field=models.CharField(default='', max_length=40, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='nombreComprador',
            field=models.CharField(max_length=40, verbose_name='Nombre del comprador'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='nombreVendedor',
            field=models.CharField(max_length=40, verbose_name='Nombre del vendedor'),
        ),
    ]
